/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminshellRouteRouteImport } from './routes/_adminshell/route'
import { Route as SalonshellRouteRouteImport } from './routes/_salonshell/route'
import { Route as BookingStatusRouteImport } from './routes/booking-status'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BookSalonSlugRouteImport } from './routes/book/$salonSlug'
import { Route as AdminshellAdminIndexRouteImport } from './routes/_adminshell/admin/index'
import { Route as AdminshellAdminApprovalsRouteImport } from './routes/_adminshell/admin/approvals'
import { Route as AdminshellAdminPlansRouteImport } from './routes/_adminshell/admin/plans'
import { Route as AdminshellAdminReportsRouteImport } from './routes/_adminshell/admin/reports'
import { Route as SalonshellAppIndexRouteImport } from './routes/_salonshell/app/index'
import { Route as SalonshellAppReportsRouteImport } from './routes/_salonshell/app/reports'
import { Route as SalonshellAppSettingsRouteImport } from './routes/_salonshell/app/settings'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminshellRouteRoute = AdminshellRouteRouteImport.update({
  id: '/_adminshell',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonshellRouteRoute = SalonshellRouteRouteImport.update({
  id: '/_salonshell',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingStatusRoute = BookingStatusRouteImport.update({
  id: '/booking-status',
  path: '/booking-status',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSalonSlugRoute = BookSalonSlugRouteImport.update({
  id: '/book/$salonSlug',
  path: '/book/$salonSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminshellAdminIndexRoute = AdminshellAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminshellRouteRoute,
} as any)
const AdminshellAdminApprovalsRoute =
  AdminshellAdminApprovalsRouteImport.update({
    id: '/admin/approvals',
    path: '/admin/approvals',
    getParentRoute: () => AdminshellRouteRoute,
  } as any)
const AdminshellAdminPlansRoute = AdminshellAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AdminshellRouteRoute,
} as any)
const AdminshellAdminReportsRoute = AdminshellAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminshellRouteRoute,
} as any)
const SalonshellAppIndexRoute = SalonshellAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => SalonshellRouteRoute,
} as any)
const SalonshellAppReportsRoute = SalonshellAppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => SalonshellRouteRoute,
} as any)
const SalonshellAppSettingsRoute = SalonshellAppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => SalonshellRouteRoute,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-status': typeof BookingStatusRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$salonSlug': typeof BookSalonSlugRoute
  '/admin/approvals': typeof AdminshellAdminApprovalsRoute
  '/admin/plans': typeof AdminshellAdminPlansRoute
  '/admin/reports': typeof AdminshellAdminReportsRoute
  '/app/reports': typeof SalonshellAppReportsRoute
  '/app/settings': typeof SalonshellAppSettingsRoute
  '/admin/': typeof AdminshellAdminIndexRoute
  '/app/': typeof SalonshellAppIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-status': typeof BookingStatusRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$salonSlug': typeof BookSalonSlugRoute
  '/admin/approvals': typeof AdminshellAdminApprovalsRoute
  '/admin/plans': typeof AdminshellAdminPlansRoute
  '/admin/reports': typeof AdminshellAdminReportsRoute
  '/app/reports': typeof SalonshellAppReportsRoute
  '/app/settings': typeof SalonshellAppSettingsRoute
  '/admin': typeof AdminshellAdminIndexRoute
  '/app': typeof SalonshellAppIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminshell': typeof AdminshellRouteRouteWithChildren
  '/_salonshell': typeof SalonshellRouteRouteWithChildren
  '/booking-status': typeof BookingStatusRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/book/$salonSlug': typeof BookSalonSlugRoute
  '/_adminshell/admin/approvals': typeof AdminshellAdminApprovalsRoute
  '/_adminshell/admin/plans': typeof AdminshellAdminPlansRoute
  '/_adminshell/admin/reports': typeof AdminshellAdminReportsRoute
  '/_salonshell/app/reports': typeof SalonshellAppReportsRoute
  '/_salonshell/app/settings': typeof SalonshellAppSettingsRoute
  '/_adminshell/admin/': typeof AdminshellAdminIndexRoute
  '/_salonshell/app/': typeof SalonshellAppIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-status'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/login'
    | '/book/$salonSlug'
    | '/admin/approvals'
    | '/admin/plans'
    | '/admin/reports'
    | '/app/reports'
    | '/app/settings'
    | '/admin/'
    | '/app/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-status'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/login'
    | '/book/$salonSlug'
    | '/admin/approvals'
    | '/admin/plans'
    | '/admin/reports'
    | '/app/reports'
    | '/app/settings'
    | '/admin'
    | '/app'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_adminshell'
    | '/_salonshell'
    | '/booking-status'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/login'
    | '/book/$salonSlug'
    | '/_adminshell/admin/approvals'
    | '/_adminshell/admin/plans'
    | '/_adminshell/admin/reports'
    | '/_salonshell/app/reports'
    | '/_salonshell/app/settings'
    | '/_adminshell/admin/'
    | '/_salonshell/app/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminshellRouteRoute: typeof AdminshellRouteRouteWithChildren
  SalonshellRouteRoute: typeof SalonshellRouteRouteWithChildren
  BookingStatusRoute: typeof BookingStatusRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BookSalonSlugRoute: typeof BookSalonSlugRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminshell': {
      id: '/_adminshell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminshellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_salonshell': {
      id: '/_salonshell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SalonshellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-status': {
      id: '/booking-status'
      path: '/booking-status'
      fullPath: '/booking-status'
      preLoaderRoute: typeof BookingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$salonSlug': {
      id: '/book/$salonSlug'
      path: '/book/$salonSlug'
      fullPath: '/book/$salonSlug'
      preLoaderRoute: typeof BookSalonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminshell/admin/': {
      id: '/_adminshell/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminshellAdminIndexRouteImport
      parentRoute: typeof AdminshellRouteRoute
    }
    '/_adminshell/admin/approvals': {
      id: '/_adminshell/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminshellAdminApprovalsRouteImport
      parentRoute: typeof AdminshellRouteRoute
    }
    '/_adminshell/admin/plans': {
      id: '/_adminshell/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminshellAdminPlansRouteImport
      parentRoute: typeof AdminshellRouteRoute
    }
    '/_adminshell/admin/reports': {
      id: '/_adminshell/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminshellAdminReportsRouteImport
      parentRoute: typeof AdminshellRouteRoute
    }
    '/_salonshell/app/': {
      id: '/_salonshell/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof SalonshellAppIndexRouteImport
      parentRoute: typeof SalonshellRouteRoute
    }
    '/_salonshell/app/reports': {
      id: '/_salonshell/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof SalonshellAppReportsRouteImport
      parentRoute: typeof SalonshellRouteRoute
    }
    '/_salonshell/app/settings': {
      id: '/_salonshell/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof SalonshellAppSettingsRouteImport
      parentRoute: typeof SalonshellRouteRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminshellRouteRouteChildren {
  AdminshellAdminApprovalsRoute: typeof AdminshellAdminApprovalsRoute
  AdminshellAdminPlansRoute: typeof AdminshellAdminPlansRoute
  AdminshellAdminReportsRoute: typeof AdminshellAdminReportsRoute
  AdminshellAdminIndexRoute: typeof AdminshellAdminIndexRoute
}

const AdminshellRouteRouteChildren: AdminshellRouteRouteChildren = {
  AdminshellAdminApprovalsRoute: AdminshellAdminApprovalsRoute,
  AdminshellAdminPlansRoute: AdminshellAdminPlansRoute,
  AdminshellAdminReportsRoute: AdminshellAdminReportsRoute,
  AdminshellAdminIndexRoute: AdminshellAdminIndexRoute,
}

const AdminshellRouteRouteWithChildren = AdminshellRouteRoute._addFileChildren(
  AdminshellRouteRouteChildren,
)

interface SalonshellRouteRouteChildren {
  SalonshellAppReportsRoute: typeof SalonshellAppReportsRoute
  SalonshellAppSettingsRoute: typeof SalonshellAppSettingsRoute
  SalonshellAppIndexRoute: typeof SalonshellAppIndexRoute
}

const SalonshellRouteRouteChildren: SalonshellRouteRouteChildren = {
  SalonshellAppReportsRoute: SalonshellAppReportsRoute,
  SalonshellAppSettingsRoute: SalonshellAppSettingsRoute,
  SalonshellAppIndexRoute: SalonshellAppIndexRoute,
}

const SalonshellRouteRouteWithChildren = SalonshellRouteRoute._addFileChildren(
  SalonshellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminshellRouteRoute: AdminshellRouteRouteWithChildren,
  SalonshellRouteRoute: SalonshellRouteRouteWithChildren,
  BookingStatusRoute: BookingStatusRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminLoginRoute: AdminLoginRoute,
  BookSalonSlugRoute: BookSalonSlugRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
