/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminshellRouteRouteImport } from './routes/_adminshell/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminshellAdminIndexRouteImport } from './routes/_adminshell/admin/index'
import { Route as AdminshellAdminPlansRouteImport } from './routes/_adminshell/admin/plans'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminshellRouteRoute = AdminshellRouteRouteImport.update({
  id: '/_adminshell',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminshellAdminIndexRoute = AdminshellAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminshellRouteRoute,
} as any)
const AdminshellAdminPlansRoute = AdminshellAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AdminshellRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminshellAdminPlansRoute
  '/admin/': typeof AdminshellAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminshellAdminPlansRoute
  '/admin': typeof AdminshellAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_adminshell': typeof AdminshellRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_adminshell/admin/plans': typeof AdminshellAdminPlansRoute
  '/_adminshell/admin/': typeof AdminshellAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/login' | '/admin/plans' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/login' | '/admin/plans' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_adminshell'
    | '/admin/login'
    | '/_adminshell/admin/plans'
    | '/_adminshell/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminshellRouteRoute: typeof AdminshellRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminshell': {
      id: '/_adminshell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminshellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminshell/admin/': {
      id: '/_adminshell/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminshellAdminIndexRouteImport
      parentRoute: typeof AdminshellRouteRoute
    }
    '/_adminshell/admin/plans': {
      id: '/_adminshell/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminshellAdminPlansRouteImport
      parentRoute: typeof AdminshellRouteRoute
    }
  }
}

interface AdminshellRouteRouteChildren {
  AdminshellAdminPlansRoute: typeof AdminshellAdminPlansRoute
  AdminshellAdminIndexRoute: typeof AdminshellAdminIndexRoute
}

const AdminshellRouteRouteChildren: AdminshellRouteRouteChildren = {
  AdminshellAdminPlansRoute: AdminshellAdminPlansRoute,
  AdminshellAdminIndexRoute: AdminshellAdminIndexRoute,
}

const AdminshellRouteRouteWithChildren = AdminshellRouteRoute._addFileChildren(
  AdminshellRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminshellRouteRoute: AdminshellRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
